# theme.toml template for a Hugo theme

name = "primary-theme"
license = "MIT"
description = ""
tags = []
features = []
min_version = "0.0.1"

[author]
  name = "Weslen Martins"
  homepage = "https://www.weslenmartins.com.br"
